project:
  title: "Week 1 Practicals"
  type: website
  render:
  - index.qmd
  - Optimisation_Prac.qmd
  - Monte_Carlo_Prac.qmd
  - Bootstrap_Prac.qmd
  - Parallelisation_Prac.qmd
  output-dir: _site
website:
  title: Statistical Computing
  sidebar:
    border: true
    background: light
    position: left
  navbar:
    search: true
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Optimisation_Prac.qmd
        text: Optimisation
      - href: Monte_Carlo_Prac.qmd
        text: Monte Carlo
      - href: Bootstrap_Prac.qmd
        text: Bootstrapping
      - href: Parallelisation_Prac.qmd
        text: Parallelisation
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left